---
apiVersion: v1
kind: application
metadata:
  name: devtest.pcm-lidar
  commType: http
spec:
  services:
    - serviceName: pcm-lidar
      components:
        - componentName: pcm-lidar
          imageType: docker
          imageName: pcm-lidar
          httpPort: 10003
          interfaces:
            - interfaceName: context1
              interfaceType: http
              upstreamPath: /time
              visiblity: external
              accessList:
                - app@client
            # - interfaceName: spark-lidar-network
            #   interfaceType: network
            #   # upstreamPath: /time-2
            #   interfacePort: 10007
            #   scheme: tcp
            #   visiblity: external
            #   accessList:
            #     - app@client
          resourceProfiles:
            - resourceProfileName: default
              memory: 1024
              cpu: 1
          defaultResourceProfile: default
