---
apiVersion: v1
kind: application
metadata:
  name: devtest.spark-lidar
  commType: http
spec:
  services:
    - serviceName: spark-lidar
      components:
        - componentName: spark-lidar
          imageType: docker
          imageName: spark-lidar
          httpPort: 10003
          interfaces:
            - interfaceName: context1
              interfaceType: http
              upstreamPath: /time
              visiblity: external
              accessList:
                - app@client
            - interfaceName: spark-lidar-network
              interfaceType: network
              interfacePort: 10007
              scheme: udp
              visiblity: external
              accessList:
                - app@client
          resourceProfiles:
            - resourceProfileName: default
              memory: 1024
              cpu: 1
          defaultResourceProfile: default
